[2022-10-26 13:33:10,917] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportes_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:33:10,961] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportes_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:33:10,961] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:33:10,962] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 13:33:10,963] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:33:11,006] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): deportes_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 13:33:11,081] {standard_task_runner.py:52} INFO - Started process 345 to run task
[2022-10-26 13:33:11,110] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'deportes_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpbkrlarnx', '--error-file', '/tmp/tmpc2uiceoa']
[2022-10-26 13:33:11,114] {standard_task_runner.py:80} INFO - Job 4: Subtask deportes_raw_create
[2022-10-26 13:33:11,309] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.deportes_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host b1681a16582a
[2022-10-26 13:33:11,658] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=deportes_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 13:33:11,903] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres-default` isn't defined
[2022-10-26 13:33:11,938] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=load_raw_data, task_id=deportes_raw_create, execution_date=20220901T000000, start_date=20221026T133310, end_date=20221026T133311
[2022-10-26 13:33:12,029] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task deportes_raw_create (The conn_id `postgres-default` isn't defined; 345)
[2022-10-26 13:33:12,098] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-26 13:33:12,319] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:27:29,113] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportes_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:29,139] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportes_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:29,139] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:29,139] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:27:29,140] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:29,198] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): deportes_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:27:29,206] {standard_task_runner.py:52} INFO - Started process 249 to run task
[2022-10-26 14:27:29,229] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'deportes_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpz3ohp__i', '--error-file', '/tmp/tmpls7p6f2p']
[2022-10-26 14:27:29,232] {standard_task_runner.py:80} INFO - Job 4: Subtask deportes_raw_create
[2022-10-26 14:27:29,533] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.deportes_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host d860ef10ab5f
[2022-10-26 14:27:30,437] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=deportes_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:27:30,613] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:27:30,677] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS deportes_raw (deporte_id serial primary key,
                                                                                deporte varchar(100));
                        , parameters: None
[2022-10-26 14:27:30,988] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=deportes_raw_create, execution_date=20220901T000000, start_date=20221026T142729, end_date=20221026T142730
[2022-10-26 14:27:31,028] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:27:31,215] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:47:44,251] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportes_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:44,297] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportes_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:44,297] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:44,298] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:47:44,298] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:44,340] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): deportes_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:47:44,350] {standard_task_runner.py:52} INFO - Started process 282 to run task
[2022-10-26 14:47:44,364] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'deportes_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpcv8nvd6c', '--error-file', '/tmp/tmp040rx7_p']
[2022-10-26 14:47:44,366] {standard_task_runner.py:80} INFO - Job 3: Subtask deportes_raw_create
[2022-10-26 14:47:44,505] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.deportes_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 4af2e895db31
[2022-10-26 14:47:44,702] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=deportes_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:47:44,734] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:47:44,740] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS deportes_raw (deporte_id serial primary key,
                                                                                deporte varchar(100));
                        , parameters: None
[2022-10-26 14:47:44,778] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=deportes_raw_create, execution_date=20220901T000000, start_date=20221026T144744, end_date=20221026T144744
[2022-10-26 14:47:44,828] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:47:44,963] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 17:10:49,514] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportes_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 17:10:49,620] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportes_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 17:10:49,620] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 17:10:49,620] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 17:10:49,621] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 17:10:49,779] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): deportes_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 17:10:49,802] {standard_task_runner.py:52} INFO - Started process 251 to run task
[2022-10-26 17:10:49,936] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'deportes_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp8ik04472', '--error-file', '/tmp/tmpch20bl04']
[2022-10-26 17:10:49,957] {standard_task_runner.py:80} INFO - Job 2: Subtask deportes_raw_create
[2022-10-26 17:10:50,801] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.deportes_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 553edc2a1daa
[2022-10-26 17:10:51,439] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=deportes_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 17:10:51,527] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 17:10:51,544] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS deportes_raw (deporte_id serial primary key,
                                                                                deporte varchar(100));
                        , parameters: None
[2022-10-26 17:10:51,728] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=deportes_raw_create, execution_date=20220901T000000, start_date=20221026T171049, end_date=20221026T171051
[2022-10-26 17:10:51,895] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 17:10:52,051] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
