[2022-10-26 13:37:52,904] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:37:52,926] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:37:52,927] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:37:52,927] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 13:37:52,927] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:37:52,955] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): deportistas_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 13:37:52,961] {standard_task_runner.py:52} INFO - Started process 465 to run task
[2022-10-26 13:37:52,971] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'deportistas_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpn4r1yv3c', '--error-file', '/tmp/tmp71tn6m9b']
[2022-10-26 13:37:52,973] {standard_task_runner.py:80} INFO - Job 20: Subtask deportistas_raw_create
[2022-10-26 13:37:53,164] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host b1681a16582a
[2022-10-26 13:37:53,321] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=deportistas_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 13:37:53,336] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 13:37:53,343] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS deportistas_raw (deportista_id serial primary key,
                                                                                    nombre varchar(100),
                                                                                    genero_id integer REFERENCES generos_raw (genero_id),
                                                                                    edad integer,
                                                                                    altura integer,
                                                                                    peso numeric,
                                                                                    equipo_id integer REFERENCES equipos_raw (equipo_id));
                        , parameters: None
[2022-10-26 13:37:53,449] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=deportistas_raw_create, execution_date=20220901T000000, start_date=20221026T133752, end_date=20221026T133753
[2022-10-26 13:37:53,501] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 13:37:53,591] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:27:34,637] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:34,657] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:34,658] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:34,658] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:27:34,658] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:34,677] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): deportistas_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:27:34,682] {standard_task_runner.py:52} INFO - Started process 265 to run task
[2022-10-26 14:27:34,687] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'deportistas_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp46xv307w', '--error-file', '/tmp/tmpi9u_b_1l']
[2022-10-26 14:27:34,688] {standard_task_runner.py:80} INFO - Job 11: Subtask deportistas_raw_create
[2022-10-26 14:27:34,763] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host d860ef10ab5f
[2022-10-26 14:27:34,882] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=deportistas_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:27:34,895] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:27:34,900] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS deportistas_raw (deportista_id serial primary key,
                                                                                    nombre varchar(100),
                                                                                    genero_id integer REFERENCES generos_raw (genero_id),
                                                                                    edad integer,
                                                                                    altura integer,
                                                                                    peso numeric,
                                                                                    equipo_id integer REFERENCES equipos_raw (equipo_id));
                        , parameters: None
[2022-10-26 14:27:34,940] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=deportistas_raw_create, execution_date=20220901T000000, start_date=20221026T142734, end_date=20221026T142734
[2022-10-26 14:27:34,979] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:27:35,041] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:47:49,022] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:49,036] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:49,036] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:49,036] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:47:49,036] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:49,055] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): deportistas_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:47:49,061] {standard_task_runner.py:52} INFO - Started process 305 to run task
[2022-10-26 14:47:49,065] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'deportistas_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpe2dk6jb8', '--error-file', '/tmp/tmpa3kr9daw']
[2022-10-26 14:47:49,067] {standard_task_runner.py:80} INFO - Job 12: Subtask deportistas_raw_create
[2022-10-26 14:47:49,153] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 4af2e895db31
[2022-10-26 14:47:49,272] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=deportistas_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:47:49,287] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:47:49,292] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS deportistas_raw (deportista_id serial primary key,
                                                                                    nombre varchar(100),
                                                                                    genero_id integer REFERENCES generos_raw (genero_id),
                                                                                    edad integer,
                                                                                    altura integer,
                                                                                    peso numeric,
                                                                                    equipo_id integer REFERENCES equipos_raw (equipo_id));
                        , parameters: None
[2022-10-26 14:47:49,323] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=deportistas_raw_create, execution_date=20220901T000000, start_date=20221026T144749, end_date=20221026T144749
[2022-10-26 14:47:49,359] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:47:49,419] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 17:10:55,930] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 17:10:55,988] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 17:10:55,989] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 17:10:55,989] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 17:10:55,989] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 17:10:56,059] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): deportistas_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 17:10:56,067] {standard_task_runner.py:52} INFO - Started process 264 to run task
[2022-10-26 17:10:56,071] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'deportistas_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmplpi9qpx_', '--error-file', '/tmp/tmp4zu8z2re']
[2022-10-26 17:10:56,073] {standard_task_runner.py:80} INFO - Job 11: Subtask deportistas_raw_create
[2022-10-26 17:10:56,228] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 553edc2a1daa
[2022-10-26 17:10:56,524] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=deportistas_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 17:10:56,545] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 17:10:56,553] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS deportistas_raw (deportista_id serial primary key,
                                                                                    nombre varchar(100),
                                                                                    genero_id integer REFERENCES generos_raw (genero_id),
                                                                                    edad integer,
                                                                                    altura integer,
                                                                                    peso numeric,
                                                                                    equipo_id integer REFERENCES equipos_raw (equipo_id));
                        , parameters: None
[2022-10-26 17:10:56,746] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=deportistas_raw_create, execution_date=20220901T000000, start_date=20221026T171055, end_date=20221026T171056
[2022-10-26 17:10:56,847] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 17:10:57,003] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-29 18:23:17,346] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-29 18:23:17,409] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-29 18:23:17,410] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-29 18:23:17,410] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-29 18:23:17,410] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-29 18:23:17,495] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): deportistas_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-29 18:23:17,510] {standard_task_runner.py:52} INFO - Started process 223 to run task
[2022-10-29 18:23:17,521] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'deportistas_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp6wi2or7z', '--error-file', '/tmp/tmpezkwq8xr']
[2022-10-29 18:23:17,522] {standard_task_runner.py:80} INFO - Job 12: Subtask deportistas_raw_create
[2022-10-29 18:23:17,674] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.deportistas_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host d3faad85a14a
[2022-10-29 18:23:17,825] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=deportistas_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-29 18:23:17,838] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-29 18:23:17,843] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS oly.deportistas_raw (deportista_id serial primary key,
                                                                                    nombre varchar(100),
                                                                                    genero_id integer REFERENCES generos_raw (genero_id),
                                                                                    edad integer,
                                                                                    altura integer,
                                                                                    peso numeric,
                                                                                    equipo_id integer REFERENCES equipos_raw (equipo_id));
                        , parameters: None
[2022-10-29 18:23:17,855] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 188, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 212, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "generos_raw" does not exist

[2022-10-29 18:23:17,869] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=load_raw_data, task_id=deportistas_raw_create, execution_date=20220901T000000, start_date=20221029T182317, end_date=20221029T182317
[2022-10-29 18:23:17,894] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task deportistas_raw_create (relation "generos_raw" does not exist
; 223)
[2022-10-29 18:23:17,942] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-29 18:23:18,005] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
